#!/usr/bin/env bash
#This script sets up an Ubuntu server with specific configurations:
#The localhost is configured to resolve to 127.0.0.2
#The domain facebook.com is set to resolve to the IP address 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i 's/.*localhost/127.0.0.2 localhost/g' ~/hosts.new
sed -i 's/.*facebook.com//g' ~/hosts.new
sed -i '1 a 8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
