#!/usr/bin/env bash
#This script retrieves and displays a list of all currently active IPv4 addresses on the machine where it is executed.
ifconfig | grep -Eo "inet (addr:)?([0-9].){3}[0-9]" | cut -b 11-
